CREATE TABLE IF NOT EXISTS role (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS users (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname    TEXT,
  lastname     TEXT,
  birthdate    DATE,
  address      TEXT,
  phone        INTEGER,
  email        TEXT,
  documentId  TEXT,
  base_salary NUMERIC(19,2)
   -- 1:1 con roles
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_user_email_ci
  ON users (lower(email))
  WHERE email IS NOT NULL;