CREATE TABLE IF NOT EXISTS role (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT
);

CREATE TABLE IF NOT EXISTS users (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname    TEXT NOT NULL ,
  lastname     TEXT NOT NULL,
  birthdate    DATE,
  address      TEXT,
  phone        INTEGER,
  email        TEXT NOT NULL UNIQUE,
  documentId  TEXT NOT NULL UNIQUE,
  base_salary NUMERIC(19,2) NOT NULL,
  password TEXT NOT NULL,
  role_id BIGINT NOT NULL,
    CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES role(id)
   -- 1:1 con roles
);